# frozen_string_literal: true

require "nokogiri"
require_relative "lint/errors"
require_relative "lint/version"
require_relative "lint/offense"
require_relative "lint/call_node"
require_relative "lint/ruby_code"
require_relative "lint/block_inspection"
require_relative "lint/slim_node"
require_relative "lint/erb_element_node"
require_relative "lint/erb_output_node"
require_relative "lint/phlex_tags"
require_relative "lint/phlex_node"
require_relative "lint/configuration"
require_relative "lint/node_rule"
Dir[File.join(__dir__, "lint", "rules", "**", "*.rb")].each { |f| require f }
require_relative "lint/slim_runner"
require_relative "lint/erb_runner"
require_relative "lint/phlex_runner"
