# frozen_string_literal: true

require "nokogiri"
require_relative "lint/errors"
require_relative "lint/version"
require_relative "lint/offense"
require_relative "lint/ruby_code_parser"
require_relative "lint/slim_node"
require_relative "lint/erb_node"
require_relative "lint/phlex_tags"
require_relative "lint/phlex_node"
require_relative "lint/configuration"
require_relative "lint/rule"
require_relative "lint/rules/perceivable/image_tag_missing_alt"
require_relative "lint/rules/perceivable/img_missing_alt"
require_relative "lint/rules/perceivable/list_invalid_children"
require_relative "lint/rules/robust/missing_accessible_name"
require_relative "lint/slim_runner"
require_relative "lint/erb_runner"
require_relative "lint/phlex_runner"
